### PR TITLE
Core image optimize

### PR DESCRIPTION
**Pull request by highcup**
Core images size went from 1.76GB and 31 layers to 972MB and 29 layers.

Changed base image from ruby:2.7.0 to ruby:2.7.0-slim-buster
Moved libvips complilation to it's own stage.
Moved gem installation and building to it's own stage.
Removed node, node_modules, and yarn after recompiling rails assets.

### CODE REVIEW

**Comment by noirscape** [comment]
Getting
```
 error: Errno::ENOENT - No such file or directory - vips 
```
when attempting to upload a gif. Vips doesn't appear to be properly set up.

e621 runs vips as a binary, not as a library it seems. Modifying dockerfile to test if we just need the binary or if we also need the libvips files.

next update; okay the library and the binary are needed.

**Comment by highcup** [comment]
With a fresh build of commit 41d19c48a7397629767cb301f0fca91f0af69c95 I was able to upload the following three gifs. Can you give me a link to the gif that gave you that error?

https://static1.e926.net/data/f1/6f/f16f426c55db7242049c6b569a0f60cb.gif
https://static1.e926.net/data/64/09/6409dbe29d0580247b9823d1366ec188.gif
https://cdn.discordapp.com/emojis/731548844252332213.gif

**Comment by noirscape** [comment]
This is the GIF I tried recently, but it happens with all GIFs: https://static1.e621.net/data/af/cd/afcd108414cbfea24281202f0d1cf702.gif

The issue is that there's no vips binary in the PATH. Adding an extra stage to copy the binary (`COPY --from vips-builder /usr/bin/vips /usr/bin/vips`) fixes it.

**Comment by highcup** [comment]
Try it now. I pushed the fix that also copies the vips binary. Though I do have to say it's pretty weird that I was able to upload gifs to me instance without the binary. Are gifs the only file format you had a problem with?

**Comment by noirscape** [comment]
GIFs should be the only format to cause issues, since all E621 uses Vips for is to check if there's a second frame on a GIF[1]. 

As to why it worked on your case, did you bring down the instance completely beforer rebuilding your images? Just stopping the containers doesn't actually update them from my experience (you need to run `docker-compose down`).

Anyway, this one now works. Merging it into master now. Thanks a lot for the contribution.

[1]: https://github.com/zwagoth/e621ng/blob/b30d7ac72997ab35160745d846d678ed2da295f4/app/logical/upload_service/utils.rb

**Comment by highcup** [comment]
You're welcome. I am glad to help. 

I actually deleted all docker images and the contents of the data folder when I tested and worked without the vips binary.  Well I am glad it's working now.

**Pull request merged**
